---

apiVersion: v1
kind : ConfigMap
metadata:
  name: mongodb-configmap
data:
  db_host: mongodb-service


---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username:
  password:

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  mduser: (username and password of mongodb)
  mdpass:
  meuser:
  mepass: (username and password of mongoexpress)

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels: 
    app: mongodb
spec:
  replicas: 1
  selector: 
    matchlabels:
      app: mongodb
  templates:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db.
          volumes:
            - name: mongo-data.
              persistentVolumeClaim:
                 claimName: mongo-pvc
---
apiversion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetport: 27017

  

          
